### ISSUE TITLE
QQ登录的AppKey在哪初始化？

### ISSUE THREAD

**Issue by l123456789jy** [lingochamp/ShareLoginLib#1]
QQ登录的AppKey在哪初始化？

**Comment by echo-lgtm** [comment]
ShareBlock.getInstance().initWeibo(id) @l123456789jy

**Comment by ruancaipu** [comment]
Error:(22, 0) E:\RCPAndroid\OpenProject\Share\ShareLoginLib-master\ShareLoginLib-master\app\keystore.properties (系统找不到指定的文件。)这个怎么回事？

**Comment by echo-lgtm** [comment]
@yyloveruancaipu 你需要在自己的app目录下加入自己的签名文件keystore.properties 第三方社交登录和分析是需要签名的

**Comment by bakeny** [comment]
@echodjb 新建一个空白 keystore.properties可以么?

**Comment by echo-lgtm** [comment]
不可以

**Comment by bakeny** [comment]
@echodjb 
目前遇到两个问题:
1.导入工程报错,需要签名
![android-studio](https://cloud.githubusercontent.com/assets/12377637/7895870/bae3337e-06d6-11e5-8be2-c7d12937b2b7.png)

2.keystore.properties这个是你自定义的文件么?可否发个模板,我这边对应申请key

**Comment by echo-lgtm** [comment]
http://stackoverflow.com/questions/9019833/how-can-i-specify-location-of-debug-keystore-for-android-ant-debug-builds @bakeny 你可以参考这个

**Comment by bakeny** [comment]
@echodjb   OK  我先看看

**Comment by ruancaipu** [comment]
我是新建的keystore.properties文件，还需要手动编写吗？能不能把你这个文件内容发我看看、、3Q

**Comment by echo-lgtm** [comment]
参考上面@yyloveruancaipu
