### ISSUE TITLE
请问可否不去调用微博客户端，直接分享？

### ISSUE THREAD

**Issue by 70kg** [lingochamp/ShareLoginLib#12]
谢谢

**Comment by echo-lgtm** [comment]
微博客户端不安装也支持分享  web认证  @70kg

**Comment by 70kg** [comment]
您好，我的意思是在有微博客户端的情况下，不去调用它，直接在自己的应用内部分享出去。现在在有微博客户端的情况下，好像是默认去调用客户端分享。谢谢@echodjb
