### ISSUE TITLE
你好，项目是不是少文件了？

### ISSUE THREAD

**Issue by pengkv** [lingochamp/ShareLoginLib#2]
Error:(23) A problem occurred evaluating project ':app'.

> C:\Users\peng\Desktop\ShareLoginLib-master\ShareLoginLib-master\app\keystore.properties (系统找不到指定的文件。)

**Comment by echo-lgtm** [comment]
请参考issue1 这个问题已经close了 @pengkv

**Comment by pengkv** [comment]
好的，谢谢，感谢分享
