### ISSUE TITLE
can you upload keystore.properties ？

### ISSUE THREAD

**Issue by tosslife** [lingochamp/ShareLoginLib#3]
keystore.properties  dismiss

look look

哈哈 想看看keystore.properties 里面参数是怎么写的，感觉很规范

**Comment by echo-lgtm** [comment]
storeFile=      xxxx
storePassword=  xxxxx
keyAlias=      xxxxx
keyPassword=   xxxxxx
@tosslife

**Comment by tosslife** [comment]
@echodjb tanks very much  非常感谢哦 亲

**Comment by tosslife** [comment]
你好，微信分享本地网页链接的时候，需要一个缩略图，我看到您写的是读取本地图片绝对路径，这只是其中一种，有时候可能直接分享一个app logo就可以，而且，这其中没有做判空处理，所以如果传null会崩溃
是否可以加个判空则默认选择项目logo 或者重载方法进行多态处理
Bitmap logoBitmap=BitmapFactory.decodeResource(getResources(),R.drawable.logo);

**Comment by echo-lgtm** [comment]
OK,thanks @tosslife

**Comment by tosslife** [comment]
@echodjb  幸好你说的英语我还能看懂，哈哈哈哈哈

**Comment by tosslife** [comment]
share libray 里 引用了v7包，以及一些网络请求的开源类库，如果事先不知道会出现 引用包重复的问题，无法打包的，而且v7包由于版本号不同，可能个别同学的support版本根本没有升级，导致找不到，个人建议标明引用类库资源，libray项目中去掉v7包引用，因为貌似是新建项目时候带的，并没有实际引用。

**Comment by echo-lgtm** [comment]
引用包重复是没有问题的 可以使用 multidex 解决

**Comment by tosslife** [comment]
劳烦尽快升级下类库版本，第三方登录的部分返回用户信息室 HashMap<String, Object> userInfo 可否把 access_token 和 openid 也带回来，急 等

**Comment by echo-lgtm** [comment]
你可以根据自己的需求改进下，然后pull request 那样我可以merge进去 @tosslife

**Comment by tosslife** [comment]
遇到问题了：我用这个类库怎么微信分享后没有回调 结果呢？

**Comment by xiaoanzi** [comment]
我请教一个问题：我申请了新浪微博的AppKey. 然后再程序中初始化，然后点击按钮执行
IShareManager iShareManager = new WeiboShareManager(MainActivity.this);
iShareManager.share(new ShareContentText("test"), WeiboShareManager.WEIBO_SHARE_TYPE);
这段代码，但是为什么没有反应呢？

**Comment by echo-lgtm** [comment]
你的app 签名了吗？@xiaoanzi

**Comment by echo-lgtm** [comment]
微信分享需要app签名了才能试用 @tosslife

**Comment by xiaoanzi** [comment]
哦，没有。我新建的一个项目来做测试，小白，还有点弄不明白，嘿嘿。非常感谢你哈。

**Comment by tosslife** [comment]
@echodjb 当然签名了，而且微信中也分享成功了，只是 WXEntryActivity 继承你的activity 但是就没有毁掉了，我试了如果不继承你的activity 可以有回调

**Comment by xiaoanzi** [comment]
再次请教@echodjb，我app签了名还是没有反应啊，控制台输出了一个错误
 E/WifiManager﹕ mWifiServiceMessenger == null  但是应该没有影响吧？
下面是我的bulid.gradle的配置：
android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"
    signingConfigs {
        release {
            keyAlias 'sharet'
            keyPassword '1234567'
            storeFile file('C:/Users/wang/sharetest.jks')
            storePassword '123456'
        }
    }
    defaultConfig {
        applicationId "com.example.wang.shareloginlibtest"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        debug {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
}
弄了很久不知道错在哪里....
难道是我的新浪App Key出了问题？我在新浪开放平台创建的应用是处在“开发”状态，我还没有提交审核....

**Comment by echo-lgtm** [comment]
是去微博那边签名。。具体看微博开放平台@xiaoanzi

**Comment by xiaoanzi** [comment]
嗯。。成功了。谢谢~
