### ISSUE TITLE
导入Android Studio后报错

### ISSUE THREAD

**Issue by zhengxiaochuan** [lingochamp/ShareLoginLib#8]
把该项目clone下来后，直接导入到Android Studio中就报错，错误内容是：

错误: 程序包retrofit.client不存在

希望能够修复，谢谢

**Comment by zhengxiaochuan** [comment]
完整的错误，我还是截图吧

**Comment by echo-lgtm** [comment]
revert回来了 重新pull下吧 @zhengxiaochuan

**Comment by zhengxiaochuan** [comment]
重新pull过了，又出现了新的错误，我的studio是1.3.1的，你的环境可以运行起来吗？

Failed to sync Gradle project 'ShareLoginLib'

Error:Unable to find method 'org.gradle.api.internal.project.ProjectInternal.getPluginManager()Lorg/gradle/api/internal/plugins/PluginManagerInternal;'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by echo-lgtm** [comment]
这个你可以注释掉  这是我用来更新版本的。 不影响你调试代码 @zhengxiaochuan
